version: '3.1'
services:
  marble-db:
    image: postgres:15.0
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - event-manager-db-volume:/var/lib/postgresql/data

volumes:
  event-manager-db-volume:
